### ISSUE TITLE
Error fetching sitemap

### ISSUE THREAD

**Issue by fireworksordie** [timf34/Substack2Markdown#9]
I cloned the repository as instructed and installed the requirements (best I can tell) and am getting this error:

```
Error fetching sitemap: 404
0it [00:00, ?it/s]
```

I tried setting to login as well just in case. Any idea what I can do to fix this?
Thanks for the tool - excited to hopefully be able to use it!

**Comment by timf34** [comment]
Hi there, 

Could you share the url you're trying it on? 
Thanks

**Comment by godofecht** [comment]
I'm facing the same issue. When did you create your account?

**Comment by timf34** [comment]
Sorry for the delay guys, I'll try replicate this later today with that substack link!

**Comment by fireworksordie** [comment]
absolutely not reason to apologize. but thank you! let me know if i can be
helpful in any way.

**Comment by timf34** [comment]
Ok so I've just had a quick look at things, and it seems that your substack doesn't have a sitemap.xml file. 

Here is a substack with it for example https://www.astralcodexten.com/sitemap.xml 

But if I go to: https://yellowcarding.substack.com/sitemap.xml, it says "This publication does not have a sitemap". 

I don't really understand why would you not have one tbh, it's the sort of thing that Substack should generate automatically ([says here that they do, but it can take a while](https://www.byburk.net/getting-your-substack-indexed-on-google-search/#:~:text=A%20sitemap%20is%20an%20XML%20file%20listing%20every%20URL/page%20on%20your%20site.%20Substack%20automatically%20generates%20a%20sitemap%20for%20publications.)) as it'll be used by Google or such to help have your blog show up on their search feed. 

Perhaps you can email Substack directly in case your blog was somehow missed and ask them to generate your sitemap.xml? 

For context, we use the sitemap.xml the same way that Google would, to get a list of all the URLs for your blog posts (otherwise we'd have to manually click the load more page/ scroll down, which isn't trivial to do)

**Comment by timf34** [comment]
Let me know how you get on with substack wrt getting a sitemap.xml!

Another option would be to use a substack's feed.rss which I can see that you do have, however looking at other Substacks, this RSS feed seems to max out at only showing the 22 most recent articles for some reason and its quite structurally different to a sitemap.xml which could take a while, which isn't ideal.

**Comment by godofecht** [comment]
How can we help? Querying my own SubStack is necessary for a project I'm already working on... so anything to help speed up the process.

Also, how do we obtain a sitemap.xml file from SubStack?

**Comment by timf34** [comment]
I unfortunately don't have a personal blog on substack so don't have direct experience with this, but I think emailing substack support would be a good shout. The site I linked above said they should generate this automatically but that it can be slow sometimes

**Comment by fireworksordie** [comment]
i've sent in a support note about getting a sitemap.xml generated (after their AI support chat was surprisingly aware of the issue but unable to solve it) and i'll report back if/when that's successful. in the meantime i know the RSS feed doesn't cover all bases but it might still be worth falling back on for users who don't have a sitemap but also not too many posts.

**Comment by timf34** [comment]
Thanks for the update! Keep us posted - I gave the feed.xml a quick look there and it should be easier to scrape than I first thought, let me have a quick go

**Comment by timf34** [comment]
@fireworksordie try out the latest code, it should work now with your feed.xml! 

The issue seemed to close automatically as I included "fixed #9" in my commit message, but please let us know how you get on with the sitemap.xml, that could be useful for others!

And would appreciate giving a star if you find this useful!

**Comment by godofecht** [comment]
Legendary

**Comment by fireworksordie** [comment]
just wanted to say i both had little success asking support for the sitemap to be generated but that i also just had a chance to try the update and the fallback worked wonderfully. thank you <3
